global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'localhost:9090'
  - job_name: 'frugalos'
    static_configs:
      - targets:
        - 'host.docker.internal:3000' # デフォルトではfrugalosはポート3000を使う
  - job_name: 'node_exporter'
    static_configs:
      - targets: ["host.docker.internal:9100"]
    relabel_configs:
      - source_labels: ['instance']
        replacement: 'frugalos'
        target_label: 'instance'
